# Generated by Django 2.0.6 on 2018-07-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20180706_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='blurb',
            field=models.TextField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='github_link',
            field=models.URLField(default='none'),
        ),
    ]
