# Generated by Django 2.0.6 on 2018-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20180709_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='summary',
        ),
        migrations.AddField(
            model_name='job',
            name='content',
            field=models.TextField(default='testing', max_length=2000),
            preserve_default=False,
        ),
    ]
